<?php

if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group([
        'key' => 'group_639066bd9a292',
        'title' => __('Block - Banner (Slider)', 'oo_theme'),
        'fields' => [
            [
                'key' => 'field_64f59dd5899d2',
                'label' => __(
                    '<span class="dashicons dashicons-edit"></span> Inhalt',
                    'oo_theme',
                ),
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'hide_field' => '',
                'hide_label' => '',
                'hide_instructions' => '',
                'hide_required' => '',
                'wpml_cf_preferences' => 3,
                'required_message' => '',
                'placement' => 'top',
                'endpoint' => 0,
                'no_preference' => 0,
                'instruction_placement' => '',
                'acfe_permissions' => '',
                'selected' => 0,
            ],
            [
                'key' => 'field_64d353118051b',
                'label' => __('Slider', 'oo_theme'),
                'name' => 'slider',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'hide_field' => '',
                'hide_label' => '',
                'hide_instructions' => '',
                'hide_required' => '',
                'wpml_cf_preferences' => 3,
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'block',
                'pagination' => 0,
                'acfe_settings' => '',
                'min' => 1,
                'max' => 5,
                'instruction_placement' => '',
                'acfe_permissions' => '',
                'collapsed' => '',
                'button_label' => __('Element hinzufügen', 'oo_theme'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    [
                        'key' => 'field_64d3528880518',
                        'label' => __(
                            '<span class="dashicons dashicons-edit"></span> Inhalt',
                            'oo_theme',
                        ),
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'required_message' => '',
                        'placement' => 'top',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'parent_repeater' => 'field_64d353118051b',
                        'selected' => 0,
                    ],
                    [
                        'key' => 'field_64d355488051c',
                        'label' => __('Hintergrund auswählen', 'oo_theme'),
                        'name' => 'background',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'choices' => [
                            'color' => __('Hintergrundfarbe', 'oo_theme'),
                            'image' => __('Bild', 'oo_theme'),
                            'video' => __('Video', 'oo_theme'),
                        ],
                        'default_value' => 'image',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'max' => '',
                        'prepend' => '',
                        'append' => '',
                        'acfe_settings' => '',
                        'acfe_validate' => '',
                        'required_message' => '',
                        'allow_null' => 0,
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'min' => '',
                        'parent_repeater' => 'field_64d353118051b',
                        'create_options' => 0,
                        'save_options' => 0,
                    ],
                    [
                        'key' => 'field_64d35a258051e',
                        'label' => __('Bild', 'oo_theme'),
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355488051c',
                                    'operator' => '==',
                                    'value' => 'image',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'uploader' => '',
                        'return_format' => 'array',
                        'upload_folder' => '',
                        'acfe_thumbnail' => 0,
                        'acfe_settings' => '',
                        'acfe_validate' => '',
                        'required_message' => '',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d35bde8051f',
                        'label' => __('Video URL', 'oo_theme'),
                        'name' => 'video',
                        'aria-label' => '',
                        'type' => 'oembed',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355488051c',
                                    'operator' => '==',
                                    'value' => 'video',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'width' => '',
                        'height' => '',
                        'acfe_settings' => '',
                        'acfe_validate' => '',
                        'required_message' => '',
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d355cb8051d',
                        'label' => __('Inhaltsart auswählen', 'oo_theme'),
                        'name' => 'type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'wpml_cf_preferences' => 3,
                        'choices' => [
                            'none' => __('Kein Inhalt', 'oo_theme'),
                            'text' => __('Text', 'oo_theme'),
                            'property-search' => __(
                                'Immobilien-Suche',
                                'oo_theme',
                            ),
                            'address-search' => __('Adress-Suche', 'oo_theme'),
                        ],
                        'default_value' => 'none',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'max' => '',
                        'prepend' => '',
                        'append' => '',
                        'required_message' => '',
                        'allow_null' => 0,
                        'allow_in_bindings' => 1,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'min' => '',
                        'parent_repeater' => 'field_64d353118051b',
                        'create_options' => 0,
                        'save_options' => 0,
                    ],
                    [
                        'key' => 'field_64d3620d175a4',
                        'label' => __('Überschrift', 'oo_theme'),
                        'name' => 'headline',
                        'aria-label' => '',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355cb8051d',
                                    'operator' => '!=',
                                    'value' => 'none',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'clone' => [
                            0 => 'group_65dc8702514b9',
                        ],
                        'display' => 'group',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 1,
                        'acfe_seamless_style' => 1,
                        'acfe_settings' => '',
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'acfe_clone_modal' => 0,
                        'acfe_clone_modal_close' => 0,
                        'acfe_clone_modal_button' => '',
                        'acfe_clone_modal_size' => 'large',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d36114175a2',
                        'label' => __('Text', 'oo_theme'),
                        'name' => 'text',
                        'aria-label' => '',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355cb8051d',
                                    'operator' => '==',
                                    'value' => 'text',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'clone' => [
                            0 => 'group_644b7c26731d4',
                        ],
                        'display' => 'group',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 1,
                        'acfe_seamless_style' => 1,
                        'acfe_settings' => '',
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'acfe_clone_modal' => 0,
                        'acfe_clone_modal_close' => 0,
                        'acfe_clone_modal_button' => '',
                        'acfe_clone_modal_size' => 'large',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d36187175a3',
                        'label' => __('Buttons', 'oo_theme'),
                        'name' => 'buttons',
                        'aria-label' => '',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355cb8051d',
                                    'operator' => '==',
                                    'value' => 'text',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'clone' => [
                            0 => 'group_6094e59f93c5d',
                        ],
                        'display' => 'group',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 1,
                        'acfe_seamless_style' => 1,
                        'acfe_settings' => '',
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'acfe_clone_modal' => 0,
                        'acfe_clone_modal_close' => 0,
                        'acfe_clone_modal_button' => '',
                        'acfe_clone_modal_size' => 'large',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d36250175a5',
                        'label' => __('Shortcode', 'oo_theme'),
                        'name' => 'shortcode',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_64d355cb8051d',
                                    'operator' => '==',
                                    'value' => 'property-search',
                                ],
                            ],
                            [
                                [
                                    'field' => 'field_64d355cb8051d',
                                    'operator' => '==',
                                    'value' => 'address-search',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'wpml_cf_preferences' => 3,
                        'default_value' => '',
                        'required_message' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 1,
                        'placeholder' => '[oo_xxxxx view="XXXXX"]',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64d353118051b',
                    ],
                    [
                        'key' => 'field_64d35c3980520',
                        'label' => __(
                            '<span class="dashicons dashicons-admin-settings"></span> Einstellungen',
                            'oo_theme',
                        ),
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'required_message' => '',
                        'placement' => 'top',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'instruction_placement' => '',
                        'acfe_permissions' => '',
                        'parent_repeater' => 'field_64d353118051b',
                        'selected' => 0,
                    ],
                    [
                        'key' => 'field_64d35c4c80521',
                        'label' => __(
                            '<span class="dashicons dashicons-admin-settings"></span> Einstellungen',
                            'oo_theme',
                        ),
                        'name' => 'settings',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'hide_field' => '',
                        'hide_label' => '',
                        'hide_instructions' => '',
                        'hide_required' => '',
                        'wpml_cf_preferences' => 3,
                        'layout' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'field_settings_clone_1',
                                'type' => 'clone',
                                'clone' => ['field_647f285fa8d83'],
                                'display' => 'seamless',
                                'prefix_name' => 0,
                            ],
                            [
                                'key' => 'field_647f285fa8e20_theme_override',
                                'label' => __(
                                    'Platzierung Inhaltselemente',
                                    'oo_theme',
                                ),
                                'name' => 'position_content',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'wpml_cf_preferences' => 3,
                                'choices' => [
                                    'left' => __(
                                        '<span class=\'dashicons dashicons-align-pull-left\' title=\'Links\'></span>',
                                        'oo_theme',
                                    ),
                                    'right' => __(
                                        '<span class=\'dashicons dashicons-align-pull-right\' title=\'Rechts\'></span>',
                                        'oo_theme',
                                    ),
                                ],
                                'default_value' => 'left',
                                'return_format' => 'value',
                                'allow_null' => 0,
                                'layout' => 'horizontal',
                            ],
                            [
                                'key' => 'field_settings_clone_3',
                                'type' => 'clone',
                                'clone' => ['field_647f285fa8f33'],
                                'display' => 'seamless',
                                'prefix_name' => 0,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_64f59ddf899d3',
                'label' => __(
                    '<span class="dashicons dashicons-admin-settings"></span> Einstellungen',
                    'oo_theme',
                ),
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'hide_field' => '',
                'hide_label' => '',
                'hide_instructions' => '',
                'hide_required' => '',
                'wpml_cf_preferences' => 3,
                'required_message' => '',
                'placement' => 'top',
                'endpoint' => 0,
                'no_preference' => 0,
                'instruction_placement' => '',
                'acfe_permissions' => '',
                'selected' => 0,
            ],
            [
                'key' => 'field_64f59e12899d4',
                'label' => __(
                    '<span class="dashicons dashicons-admin-settings"></span> Einstellungen',
                    'oo_theme',
                ),
                'name' => 'settings',
                'aria-label' => '',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'clone' => [
                    0 => 'field_647f285fa8d1c',
                ],
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
                'acfe_seamless_style' => 1,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
            ],
            [
                'key' => 'field_65001ae375c84',
                'label' => __(
                    'Seite für Immobilien-Suchergebnisse',
                    'oo_theme',
                ),
                'name' => 'property_search_result',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => __(
                    'Wählen Sie hier die Seite aus, auf welche die Suchergebnisse angezeigt werden. Z.B. die Immobilien-Übersichtsseite, Immobilienangebote, Kaufimmobilien,...
Wenn das Feld leer gelassen wird, dann wird die angegebene Seite aus den "Globalen Einstellungen" genommen.',
                    'oo_theme',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'post_type' => [
                    0 => 'page',
                ],
                'post_status' => [
                    0 => 'publish',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'max' => '',
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_add_post' => 0,
                'acfe_edit_post' => 0,
                'acfe_bidirectional' => [
                    'acfe_bidirectional_enabled' => '0',
                ],
                'allow_null' => 1,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => [],
                'save_post_type' => '',
                'min' => '',
            ],
            [
                'key' => 'field_66d9b40779195',
                'label' => __('Seite für Adress-Suchergebnisse', 'oo_theme'),
                'name' => 'address_search_result',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => __(
                    'Wählen Sie hier die Seite aus, auf welche die Suchergebnisse angezeigt werden. Z.B. die Immobilien-Übersichtsseite, Immobilienangebote, Kaufimmobilien,...
Wenn das Feld leer gelassen wird, dann wird die angegebene Seite aus den "Globalen Einstellungen" genommen.',
                    'oo_theme',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'post_type' => [
                    0 => 'page',
                ],
                'post_status' => [
                    0 => 'publish',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'max' => '',
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_add_post' => 0,
                'acfe_edit_post' => 0,
                'acfe_bidirectional' => [
                    'acfe_bidirectional_enabled' => '0',
                ],
                'allow_null' => 1,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => [],
                'save_post_type' => '',
                'min' => '',
            ],
            [
                'key' => 'field_66bf5b1819d91',
                'label' => __(
                    'Automatisches durchlaufen der Bannerinhalte',
                    'oo_theme',
                ),
                'name' => 'autoslide',
                'aria-label' => '',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'choices' => [
                    'yes' => __('Ja', 'oo_theme'),
                    'no' => __('Nein', 'oo_theme'),
                ],
                'default_value' => 'no',
                'return_format' => 'value',
                'allow_null' => 0,
                'layout' => 'horizontal',
            ],
            [
                'key' => 'field_66f7a3c9b2d45',
                'label' => __('Banneroverlay anzeigen', 'oo_theme'),
                'name' => 'banner_overlay',
                'aria-label' => '',
                'type' => 'button_group',
                'instructions' =>
                    'Das Overlay kann nur für Slides ohne Inhalt deaktiviert werden.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'choices' => [
                    'yes' => __('Ja', 'oo_theme'),
                    'no' => __('Nein', 'oo_theme'),
                ],
                'default_value' => 'yes',
                'return_format' => 'value',
                'allow_null' => 0,
                'layout' => 'horizontal',
            ],
            [
                'key' => 'field_66cf35382947d',
                'label' => '(Column 6/12)',
                'name' => '',
                'aria-label' => '',
                'type' => 'acfe_column',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 0,
                'columns' => '6/12',
                'endpoint' => 0,
                'border' => '',
                'border_endpoint' => [
                    0 => 'endpoint',
                ],
            ],
            [
                'key' => 'field_66bf5b8c788f9',
                'label' => __('Slidewechsel nach (in Sekunden)', 'oo_theme'),
                'name' => 'slide_interval',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_66bf5b1819d91',
                            'operator' => '==',
                            'value' => 'yes',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'default_value' => 5,
                'required_message' =>
                    'Bitte geben Sie die die Dauer des Slidewechsels in Sekunden an.',
                'min' => 1,
                'max' => 3600,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66bf5baa788fa',
                'label' => __('Autoslide bei Hover pausieren', 'oo_theme'),
                'name' => 'pause_on_hover',
                'aria-label' => '',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_66bf5b1819d91',
                            'operator' => '==',
                            'value' => 'yes',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'choices' => [
                    'yes' => __('Ja', 'oo_theme'),
                    'no' => __('Nein', 'oo_theme'),
                ],
                'default_value' => 'yes',
                'return_format' => 'value',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'layout' => 'horizontal',
            ],
            [
                'key' => 'field_66ce52a372913',
                'label' => __(
                    'Geschwindigkeit der Slide-Animation (in Millisekunden)',
                    'oo_theme',
                ),
                'name' => 'slide_speed',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'default_value' => 1000,
                'required_message' => '',
                'min' => 1,
                'max' => 60000,
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66cf35b02947e',
                'label' => '(Column Endpoint)',
                'name' => '',
                'aria-label' => '',
                'type' => 'acfe_column',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 0,
                'endpoint' => 1,
                'border_endpoint' => [
                    0 => 'endpoint',
                ],
                'columns' => '6/12',
                'border' => '',
            ],
            [
                'key' => 'field_66f69684faf6d',
                'label' => __(
                    '<span class="dashicon-oo-anchor">#</span> Sprungmarke / Anker-Link',
                    'oo_theme',
                ),
                'name' => 'anchor',
                'aria-label' => '',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'wpml_cf_preferences' => 3,
                'clone' => [
                    0 => 'group_66f4feef1e667',
                ],
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
                'acfe_seamless_style' => 1,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'oo/banner',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_autosync' => [
            0 => 'php',
        ],
        'acfml_field_group_mode' => 'advanced',
        'acfe_form' => 0,
        'acfe_display_title' => '',
        'acfe_meta' => '',
        'acfe_note' => '',
        'acfe_categories' => [
            'block' => 'Block',
        ],
        'modified' => 1736519114,
    ]);
endif;
